# Generated by Django 5.0.4 on 2025-02-26 17:13

from django.db import migrations


def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")

    people = PersonModel.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = "Child"
        elif 13 <= person.age <= 17:
            person.age_group = "Teen"
        elif person.age >= 18:
            person.age_group = "Adult"

        person.save()

def set_age_group_default(apss, schema_editor):
    PersonModel = apss.get_model("main_app", "Person")

    default_age_group = PersonModel._meta.get_field("age group").default

    for person in PersonModel.objects.all():
        person.age_group = default_age_group
        person.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_person'),
    ]

    operations = [
        migrations.RunPython(code=set_age_group, reverse_code=set_age_group_default)
    ]
