# Generated by Django 5.0.4 on 2025-02-27 12:48

from django.db import migrations

MULTIPLIER = 120
EXPENSIVE_THRESHOLD = 750

def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")

    for phone in SmartphoneModel.objects.all():
        phone.price = phone.brand * MULTIPLIER
        phone.save()


def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")

    for phone in SmartphoneModel.objects.all():
        phone.category = 'Cheap' if phone.price < EXPENSIVE_THRESHOLD else 'Expensive'
        phone.save()


def set_category_and_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reset_category(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    default_category = SmartphoneModel._meta.get_field("category").default

    for phone in SmartphoneModel.objects.all():
        phone.category = default_category
        phone.save()



def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get_model("main_app", "Smartphone")
    default_price = SmartphoneModel._meta.get_field("price").default

    for phone in SmartphoneModel.objects.all():
        phone.price = default_price
        phone.save()

def reset_category_and_price(apps, schema_editor):
    reset_category(apps, schema_editor)
    reset_price(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_smartphone'),
    ]

    operations = [
        migrations.RunPython(code=set_category_and_price, reverse_code=reset_category_and_price)
    ]
