# Generated by Django 5.0.4 on 2025-02-27 17:21
from datetime import timedelta

from django.db import migrations

from main_app.choices import OrderStatusChoices


def update_delivery_and_warranty(apps, schema_editor):
    OderModel = apps.get_model("main_app", "Order")

    for order in OderModel.objects.all():
        if order.status == OrderStatusChoices.PENDING:
            order.delivery = order.oder_date + timedelta(days=3)
            order.save()

        elif order.status == OrderStatusChoices.COMPLETED:
            order.warranty = '24 months'
            order.save()

        elif order.status == OrderStatusChoices.CANCELLED:
            order.delete()


class Migration(migrations.Migration):


    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
        migrations.RunPython(code=update_delivery_and_warranty)
    ]
